name: Dockerize and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest

      - name: Install Render CLI
        run: |
          curl -fsSL https://render.com/static/rcli/install.sh | bash
          echo "$HOME/.render" >> $GITHUB_PATH

      - name: Log in to Render
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services update ${{ secrets.RENDER_SERVICE_ID }} --image ${{ secrets.DOCKER_HUB_USERNAME }}/your-app:latest

      - name: Notify deployment success
        run: echo "Deployment to Render successful!"
